####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |               ███████╗██╗    ██╗██████╗  █████╗ ███╗   ██╗██╗      ██████╗  ██████╗          | #
# |               ██╔════╝██║    ██║██╔══██╗██╔══██╗████╗  ██║██║     ██╔═══██╗██╔════╝          | #
# |               █████╗  ██║ █╗ ██║██████╔╝███████║██╔██╗ ██║██║     ██║   ██║██║  ███╗         | #
# |               ██╔══╝  ██║███╗██║██╔══██╗██╔══██║██║╚██╗██║██║     ██║   ██║██║   ██║         | #
# |               ██║     ╚███╔███╔╝██████╔╝██║  ██║██║ ╚████║███████╗╚██████╔╝╚██████╔╝         | #
# |               ╚═╝      ╚══╝╚══╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝ ╚═════╝  ╚═════╝          | #
# |                                                                                              | #
# |                                     Made by: Kaotich00                                       | #
# |                                                                                              | #
# |                   SOURCE CODE: https://github.com/ForgottenWorld/FwBanlog                    | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       STORAGE SETTINGS                                       | #
# |                                                                                              | #
# |                               Configure MySQL Storage Settings                               | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Define the address and port for the database.
address: 'localhost:3306'

# The name of the database to store EasyRanking data in.
database: 'database'

# Admin Credentials for the database.
username: 'username'
password: 'password'

# Define the server id used for this server.
# Default: 1
serverId: 1