name: FwBanlog
version: ${project.version}
main: me.kaotich00.fwbanlog.FwBanlog
api-version: 1.16
authors: [ Kaotich00 ]
description: Banlog plugin for ForgottenWorlgitd Paper MC
website: https://forgottenworld.it
